# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore
      - name: Test
        run: dotnet test --no-build --verbosity normal
      - name: dotnet publish
        #      run: dotnet publish URLShortner.Api -c Release -o ${{env.DOTNET_ROOT}}/Api/src/URLShortner.Api
        run: dotnet publish ./Api/src/URLShortner.Api/URLShortner.Api.csproj -c Release -o ./publish/URLShortner.Api
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: ./Api/src/URLShortner.Api

  deploy-dev:
    runs-on: ubuntu-latest
    needs: build
    environment: Development

    steps:
      - name: Download from build
        uses: actions/download-artifact@v4
        with:
          name: .net-app

      - name: Deploy to Azure (dev)
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{vars.API_RESOURCE_NAME}}
          slot-name: "Production"
          publish-profile: ${{secrets.AZURE_API_PUBLISH_PROFILE}}
          package: "."
