# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Azure Deploy

on:
  push:
    branches:
      - main
    paths:
      - infrastructure/**
  pull_request:
    paths:
      - infrastructure/**
  workflow_dispatch:

permissions: 
  id-token: write
  contents: read
  
jobs:
  deploy-dev:
    runs-on: ubuntu-latest
    environment: Development
    steps:
      - uses: actions/checkout@v4

      - name: Azure Login
        uses: Azure/login@v2.3.0
        with:
          client-id: ${{secrets.AZURE_CLIENT_ID}}
          tenant-id: ${{secrets.AZURE_TENANT_ID}}
          subscription-id: ${{secrets.AZURE_SUBSCRIPTION_ID}}
          
      - name: Run Azure CLI commands
        uses: azure/CLI@v2
        with:
          azcliversion: 2.55.0
          scriptType: bash
          inlineScript: |
            az group create --name "${{ vars.RESOURCE_GROUP_NAME }}" --location "${{ vars.RESOURCE_GROUP_LOCATION }}"
            echo "Azure resource group created"
          
      - name: Deploy Bicep
        uses: Azure/arm-deploy@v2
        with:
          resourceGroupName: ${{vars.RESOURCE_GROUP_NAME}}
          template: ./infrastructure/main.bicep
