name: Azure Dev Deploy

on:
  workflow_dispatch:  # ręczne uruchamianie
  workflow_call:      # pozwala innym workflowom wywołać ten

permissions:
  id-token: write
  contents: read

jobs:
  deploy-dev:
    runs-on: ubuntu-latest
    environment: Development
    steps:
      - uses: actions/checkout@v4

      - name: Azure Login
        uses: Azure/login@v2.3.0
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Azure CLI script
        run: |
          az group create -l '${{ vars.RESOURCE_GROUP_LOCATION }}' -n '${{ vars.RESOURCE_GROUP_NAME }}'
          echo "Azure resource group created"

      - name: Deploy Bicep
        uses: Azure/arm-deploy@v2
        with:
          resourceGroupName: ${{vars.RESOURCE_GROUP_NAME}}
          template: ./infrastructure/main.bicep
          deploymentName: deploy-main